config/routes.rb
Rails.application.routes.draw do

  root 'pizzas#home'
  resources :pizzas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pizza.rb
class Pizza < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pizzas_controller.rb
class PizzasController < ApplicationController
  before_action :set_pizza, only: [:show, :edit, :update, :destroy,]

def home
  # code
end

  # GET /pizzas
  # GET /pizzas.json
  def index
    @pizzas = Pizza.all
  end

  # GET /pizzas/1
  # GET /pizzas/1.json
  def show
  end

  # GET /pizzas/new
  def new
    @pizza = Pizza.new
  end

  # GET /pizzas/1/edit
  def edit
  end

  # POST /pizzas
  # POST /pizzas.json
  def create
    @pizza = Pizza.new(pizza_params)

    respond_to do |format|
      if @pizza.save
        format.html { redirect_to @pizza, notice: 'Pizza was successfully created.' }
        format.json { render :show, status: :created, location: @pizza }
      else
        format.html { render :new }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pizzas/1
  # PATCH/PUT /pizzas/1.json
  def update
    respond_to do |format|
      if @pizza.update(pizza_params)
        format.html { redirect_to @pizza, notice: 'Pizza was successfully updated.' }
        format.json { render :show, status: :ok, location: @pizza }
      else
        format.html { render :edit }
        format.json { render json: @pizza.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizzas/1
  # DELETE /pizzas/1.json
  def destroy
    @pizza.destroy
    respond_to do |format|
      format.html { redirect_to pizzas_url, notice: 'Pizza was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pizza
      @pizza = Pizza.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pizza_params
      params.require(:pizza).permit(:name, :crust, :sauce, :toppings, :cost, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pizzas_helper.rb
module PizzasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>PizzaShop</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/united/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to Rails.application.class.parent_name, root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Pizzas", pizzas_url %></li>
        <li><a href="#">About</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/pizzas/_form.html.erb
<%= form_for(pizza) do |f| %>
  <% if pizza.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pizza.errors.count, "error") %> prohibited this pizza from being saved:</h2>

      <ul>
      <% pizza.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :crust %>
    <%= f.text_field :crust %>
  </div>

  <div class="field">
    <%= f.label :sauce %>
    <%= f.text_field :sauce %>
  </div>

  <div class="field">
    <%= f.label :toppings %>
    <%= f.text_area :toppings %>
  </div>

  <div class="field">
    <%= f.label :cost %>
    <%= f.number_field :cost %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizzas/edit.html.erb
<h1>Editing Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Show', @pizza %> |
<%= link_to 'Back', pizzas_path %>

app/views/pizzas/home.html.erb
<div class="jumbotron">

    <center>
        <h1>Welcome to Zack's Zas</h1>

        <img src="http://ecx.images-amazon.com/images/I/41phkELgWyL._SX342_.jpg">
        <br>

        <%= link_to "Check out our Pizzas!", pizzas_path, class: "btn btn-default" %>
    </center>
</div>

app/views/pizzas/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>All of Zack's Zas</h1>
    <div class="row">
    <% @pizzas.each do |pizza| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <img src="<%= pizza.image %>">
          <div class="caption">
            <h3><%= pizza.name %></h3>
            <h3>Cost: $<%= pizza.cost %></h3>
            <%= link_to "More Info", pizza, class: "btn btn-default" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>

    <br>

    <%= link_to 'New Pizza', new_pizza_path, class: "btn btn-primary" %>
  </body>
</html>

app/views/pizzas/new.html.erb
<h1>New Pizza</h1>

<%= render 'form', pizza: @pizza %>

<%= link_to 'Back', pizzas_path %>

app/views/pizzas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pizza.name %>
</p>

<p>
  <strong>Crust:</strong>
  <%= @pizza.crust %>
</p>

<p>
  <strong>Sauce:</strong>
  <%= @pizza.sauce %>
</p>

<p>
  <strong>Toppings:</strong>
  <%= @pizza.toppings %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @pizza.cost %>
</p>

<p>
  <strong>Image:</strong>
  <%= @pizza.image %>
</p>

<%= link_to 'Edit', edit_pizza_path(@pizza) %> |
<%= link_to 'Back', pizzas_path %>